### ISSUE TITLE
AxiosRequestAdapter used, ts reported an error

### ISSUE THREAD

**Issue by Sunny264** [alovajs/alova#90] opened 2023-05-22 07:19 UTC
### Reproduction Link

null

### alova Version

2.5.0

### Describe the Bug
```javascript
const useAlova = createAlova({
  baseURL: import.meta.env.VITE_APP_API_BASEURL,
  statesHook: VueHook,
  requestAdapter: axiosRequestAdapter(), 
  timeout: DEFAULT_TIME_OUT,
  responded: {
    onSuccess: handleResponseSuccess,
    onError: handleResponseFail,
  },
})
```

AxiosRequestAdapter used, ts reported an error, If we switch to GlobalFetch, there's no problem

```
[ts error]  Exported variable 'useAlova' has or is using name 'RawAxiosHeaders' from external module "e:/*****/node_modules/axios/index" but cannot be named.
```

### Reproduce Steps

AxiosRequestAdapter used, ts reported an error, If we switch to GlobalFetch, there's no problem
```
[TS ERROR]:  Exported variable 'useAlova' has or is using name 'RawAxiosHeaders' from external module "e:/*****/node_modules/axios/index" but cannot be named.
```

**Comment by JOU-amjs** [comment] 2023-05-22 08:11
Hi, there!🖐
I tried to reproduce issue, but it seems everything is ok.

![image](https://github.com/alovajs/alova/assets/29848971/66d34841-78c2-4d65-8844-5cf631f1af2d)

I guess the problem is `axios` package.  the `RawAxiosHeaders` is defineed in axios but it seems not found. please check below:
1. Is installed `axios`
2. Is there a problem with the Axios version, you can upgrade axios

If still not work well, please provide the version of `axios`、`@alova/adapter-axios`, and I will try to reproduce it again.

**Comment by Sunny264** [comment] 2023-05-22 08:58
> @alova/adapter-axios

Thank you very much. 
I found that it is related to the tsconfig configuration。
If I add the following configuration in compilerOptions, I will be prompted

    "declaration": true,
    "declarationDir": "./d",

**Comment by JOU-amjs** [comment] 2023-05-22 09:33
Congratulations for resolving it.🎉🎉🎉

**Closed by JOU-amjs** 2023-05-22 09:33 UTC
